"""add telegramm account info to user

Revision ID: 30866a245dd6
Revises: aca6543c182b
Create Date: 2024-10-28 17:57:46.379827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30866a245dd6'
down_revision: Union[str, None] = 'aca6543c182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_account', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('telegram_id', sa.String(length=100), nullable=True))
    op.drop_constraint('user_nick_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['telegram_account'])
    op.drop_column('user', 'nick_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nick_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_nick_name_key', 'user', ['nick_name'])
    op.drop_column('user', 'telegram_id')
    op.drop_column('user', 'telegram_account')
    # ### end Alembic commands ###
